GET https://taaft-backend.onrender.com/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODA3NjQ3ZTFhZmQzMzQ4MTc4NTUwNDIiLCJzZXJ2aWNlX3RpZXIiOiJmcmVlIiwiaXNfdmVyaWZpZWQiOnRydWUsImV4cCI6MTc0NTQ3NzczNH0.RReoc3H-QacAyfM8sNi-sTI9XJlRlArNz_C5P4hEktE

###




